#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jackson-modules-java8
Version  : java8.2.9.9
Release  : 2
URL      : https://github.com/FasterXML/jackson-modules-java8/archive/jackson-modules-java8-2.9.9.tar.gz
Source0  : https://github.com/FasterXML/jackson-modules-java8/archive/jackson-modules-java8-2.9.9.tar.gz
Source1  : https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9/jackson-datatype-jdk8-2.9.9.jar
Source2  : https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9/jackson-datatype-jdk8-2.9.9.pom
Source3  : https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-modules-java8/2.9.9/jackson-modules-java8-2.9.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jackson-modules-java8-data = %{version}-%{release}
Requires: mvn-jackson-modules-java8-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
## Overview
This is a multi-module umbrella project for [Jackson](../../../jackson)
modules needed to support Java 8 features when core Jackson modules do not
(yet) require Java 8 runtime (note: Jackson 3.0 will likely increase baseline
and allow including some or all of this functionality)

%package data
Summary: data components for the mvn-jackson-modules-java8 package.
Group: Data

%description data
data components for the mvn-jackson-modules-java8 package.


%package license
Summary: license components for the mvn-jackson-modules-java8 package.
Group: Default

%description license
license components for the mvn-jackson-modules-java8 package.


%prep
%setup -q -n jackson-modules-java8-jackson-modules-java8-2.9.9

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jackson-modules-java8
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-jackson-modules-java8/LICENSE
cp datetime/src/main/resources/META-INF/LICENSE %{buildroot}/usr/share/package-licenses/mvn-jackson-modules-java8/datetime_src_main_resources_META-INF_LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9/jackson-datatype-jdk8-2.9.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9/jackson-datatype-jdk8-2.9.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/module/jackson-modules-java8/2.9.9
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/module/jackson-modules-java8/2.9.9/jackson-modules-java8-2.9.9.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9/jackson-datatype-jdk8-2.9.9.jar
/usr/share/java/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.9/jackson-datatype-jdk8-2.9.9.pom
/usr/share/java/.m2/repository/com/fasterxml/jackson/module/jackson-modules-java8/2.9.9/jackson-modules-java8-2.9.9.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jackson-modules-java8/LICENSE
/usr/share/package-licenses/mvn-jackson-modules-java8/datetime_src_main_resources_META-INF_LICENSE
